run:
    modules-download-mode: readonly
linters-settings:
    gofmt:
        simplify: true
    errcheck:
        check-type-assertions: true
        check-blank: true
        ignore: fmt:.*,io/ioutil:^Read.*
    exhaustive:
        default-signifies-exhaustive: true
    nolintlint:
        allow-unused: true
    gocritic:
        enabled-tags:
            - diagnostic
            - experimental
            - opinionated
            - performance
            - style
        disabled-checks:
            - dupImport # https://github.com/go-critic/go-critic/issues/845
            - ifElseChain
            - octalLiteral
            - whyNoLint
            - wrapperFunc
            - unnamedResult
            - rangeValCopy # k8s api forces us to do this
linters:
    enable:
        - asciicheck
        - bodyclose
        - deadcode
        - dogsled
        # - dupl
        # - errcheck
        - exhaustive
        - exportloopref
        - gocritic
        - gofmt
        - golint
        - goprintffuncname
        - gosimple
        - govet
        - ineffassign
        - megacheck
        - misspell
        - nakedret
        - noctx
        - nolintlint
        - nolintlint
        - rowserrcheck
        - sqlclosecheck
        - staticcheck
        - structcheck
        - stylecheck
        - typecheck
        - unparam
        - unused
        - varcheck
        - whitespace
    disable-all: true
    fast: false
